# Generated by Django 5.2.6 on 2026-09-20 18:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("current_location", models.CharField(max_length=255)),
                ("current_lat", models.FloatField()),
                ("current_lon", models.FloatField()),
                ("pickup_location", models.CharField(max_length=255)),
                ("pickup_lat", models.FloatField()),
                ("pickup_lon", models.FloatField()),
                ("dropoff_location", models.CharField(max_length=255)),
                ("dropoff_lat", models.FloatField()),
                ("dropoff_lon", models.FloatField()),
                ("cycle_hours_used", models.FloatField()),
                ("start_datetime", models.DateTimeField()),
                ("arrival_datetime", models.DateTimeField()),
                ("total_distance_miles", models.FloatField()),
                ("total_driving_hours", models.FloatField()),
                ("total_on_duty_hours", models.FloatField()),
                ("total_off_duty_hours", models.FloatField()),
                ("routing_provider", models.CharField(default="", max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("query", models.CharField(max_length=255, unique=True)),
                ("results", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["query"], name="trips_geoco_query_86116c_idx")],
            },
        ),
        migrations.CreateModel(
            name="RouteCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=128, unique=True)),
                ("payload", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [models.Index(fields=["key"], name="trips_route_key_c22ee2_idx")],
            },
        ),
        migrations.CreateModel(
            name="LogDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("date", models.DateField()),
                ("total_miles", models.FloatField(default=0.0)),
                ("total_off_duty", models.FloatField(default=0.0)),
                ("total_sleeper", models.FloatField(default=0.0)),
                ("total_driving", models.FloatField(default=0.0)),
                ("total_on_duty", models.FloatField(default=0.0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="log_days",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ("day_number",),
            },
        ),
        migrations.CreateModel(
            name="DutyEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OFF_DUTY", "Off Duty"),
                            ("SLEEPER_BERTH", "Sleeper Berth"),
                            ("DRIVING", "Driving"),
                            ("ON_DUTY_NOT_DRIVING", "On Duty Not Driving"),
                        ],
                        max_length=24,
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField()),
                ("duration_hours", models.FloatField()),
                ("distance_miles", models.FloatField(default=0.0)),
                ("location_label", models.CharField(blank=True, max_length=255)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "log_day",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="trips.logday",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("log_day", "sequence"), name="unique_duty_sequence"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Stop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                (
                    "stop_type",
                    models.CharField(
                        choices=[
                            ("START", "Start"),
                            ("PICKUP", "Pickup"),
                            ("FUEL", "Fuel"),
                            ("REST_BREAK", "Rest Break"),
                            ("DAILY_RESET", "Daily Reset"),
                            ("CYCLE_RESTART", "Cycle Restart"),
                            ("DROPOFF", "Dropoff"),
                        ],
                        max_length=20,
                    ),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("location_label", models.CharField(max_length=255)),
                ("arrival_time", models.DateTimeField()),
                ("departure_time", models.DateTimeField()),
                ("duration_hours", models.FloatField()),
                ("odometer_miles", models.FloatField(default=0.0)),
                ("reason", models.CharField(blank=True, max_length=255)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stops",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("trip", "sequence"), name="unique_stop_sequence"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RouteLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("from_label", models.CharField(max_length=255)),
                ("to_label", models.CharField(max_length=255)),
                ("distance_miles", models.FloatField()),
                ("duration_hours", models.FloatField()),
                ("geometry", models.JSONField(default=list)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="trips.trip",
                    ),
                ),
            ],
            options={
                "ordering": ("sequence",),
                "constraints": [
                    models.UniqueConstraint(fields=("trip", "sequence"), name="unique_leg_sequence")
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="logday",
            constraint=models.UniqueConstraint(
                fields=("trip", "day_number"), name="unique_log_day"
            ),
        ),
    ]
