# Generated by Django 5.2.6 on 2026-09-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trip",
            name="home_timezone_offset_minutes",
            field=models.SmallIntegerField(default=0),
        ),
    ]
