# Generated by Django 5.2.6 on 2026-09-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0002_add_home_timezone_offset"),
    ]

    operations = [
        migrations.AddField(
            model_name="stop",
            name="satisfies_break",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="trip",
            name="compliance",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
