# Generated by Django 5.2.6 on 2026-09-21 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0003_add_compliance_and_break_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="NominatimThrottle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("last_request_at", models.DateTimeField(null=True)),
            ],
        ),
    ]
