# Generated by Django 5.2.6 on 2026-09-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trips", "0004_nominatim_throttle"),
    ]

    operations = [
        migrations.AddField(
            model_name="logday",
            name="cycle_hours_used_end",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
